# Generated by Django 4.2.1 on 2023-06-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='token_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_url', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
