# Generated by Django 4.2.1 on 2023-06-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_alter_app_configs_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_configs',
            name='value',
            field=models.TextField(max_length=800),
        ),
    ]
