# Generated by Django 4.2.2 on 2023-06-29 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_scripts'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripts',
            name='expiryDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
