# Generated by Django 4.2.2 on 2023-07-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_transactions_bidprice_transactions_expirydate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='parent_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
