# Generated by Django 4.2.2 on 2023-07-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_clientprofile_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='lotSize',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
