# Generated by Django 4.2.2 on 2023-07-09 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_transactions_lotsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquredOffTransactions',
            fields=[
                ('transaction_id', models.CharField(default='', editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('script_code', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('quantity', models.IntegerField()),
                ('multiplier', models.PositiveIntegerField(null=True)),
                ('lotSize', models.PositiveIntegerField(null=True)),
                ('price', models.FloatField()),
                ('action', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default='Buy', max_length=5)),
                ('expirydate', models.DateField(null=True)),
                ('offerPrice', models.PositiveIntegerField(default=0, null=True)),
                ('bidPrice', models.PositiveIntegerField(default=0, null=True)),
                ('created_by', models.CharField(default='', max_length=50)),
                ('updated_by', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.CharField(default='', max_length=100)),
                ('parent_transaction', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
