# Generated by Django 4.2.2 on 2023-07-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0011_squredofftransactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squredofftransactions',
            name='parent_transaction',
            field=models.CharField(default='', max_length=255),
        ),
    ]
