# Generated by Django 4.2.2 on 2023-07-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0012_alter_squredofftransactions_parent_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squredofftransactions',
            name='client',
            field=models.CharField(default='', max_length=50),
        ),
    ]
