# Generated by Django 4.2.2 on 2023-07-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0014_rename_client_squredofftransactions_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='squredofftransactions',
            name='profit',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
