# Generated by Django 4.2.2 on 2023-07-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0015_squredofftransactions_profit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squredofftransactions',
            old_name='profit',
            new_name='profit_loss',
        ),
        migrations.AddField(
            model_name='transactions',
            name='profit_loss',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
