# Generated by Django 4.2.2 on 2023-08-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0016_rename_profit_squredofftransactions_profit_loss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='bidPrice',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='offerPrice',
            field=models.FloatField(default=0, null=True),
        ),
    ]
